# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: ndrianja
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ndrianja
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  mongodata:
    driver: local