#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://ndrihanja:Ndrihanja07@cluster0.cdrts5u.mongodb.net/
#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false

##ze diez roa tsy izy

##spring.data.mongodb.host=api-database
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=test
server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

#app.ui.host.cors.uri_1=http://localhost:4200
#app.ui.host.cors.uri_2=http://localhost:4201